default: &default
  site_name: "Sample App"
  admin_email: "admin@example.com"
  gravatar:
    email_link: "http://gravatar.com/emails"
  

development:
  <<: *default

production:
  <<: *default
  site_name: "Sample App"


